### ISSUE TITLE
Add some automated tests

### ISSUE THREAD

**Issue by dmerejkowsky** [your-tools/lockdiff#1]
The title says it all - if we add support for other files like `yarn.lock` or `gem.lock`, we're going to need tests to ensure there's no regression

**Comment by chrisjsimpson** [comment]
What do you think the automated tests should test exactly? 

Maybe when a diff occurs in file x.lock , validate that lockdiff strips out /hides that from diff output?

The above could be automatically tested in a test which bumps a packages , commits (no pushing) , populates .gitattributes and runs lockdiff

**Comment by dmerejkowsky** [comment]
Hey, welcome to my project :)

I think we can start with a much simpler test (at the cost of a small refactoring in the production code)

I would introduce a function like

```rust
fn convert_lock(input: &str) -> String
````

And then a test that would look like this:

```rust
fn test_conversion() {
  let converted = convert_lock(r#"
    [[package]]
    name=" foo" 
    version=1.2
  "#);

  assert_eq!(&converted, "foo@1.2");
}
```

I see value in your proposal for testing more thoroughly, but I fear that what you' re proposing would be much harder to implement.

**Comment by dmerejkowsky** [comment]
Done in 4f8a22245c3fde32ee8848bee41c5a1a5c8a3182
